name: Build Test Deploy

on: push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
  build:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - run: |
          yarn install
          yarn build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - run: |
          yarn install
          yarn test
  deploy:
    needs: test
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: uses node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - name: configure github pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - run: |
          yarn install
          yarn build
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./out"
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
