name: Build Test Deploy

on: push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
  build:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - run: |
          yarn install
          yarn build
  test:
    needs: [hello-world-job, build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - run: |
          yarn install
          yarn test
